name: network_status_dialog
description: A Flutter package that shows an offline dialog when the user loses internet connection. Easily customizable with your own colors, text.
homepage: https://github.com/squarebits-sm/network-status-dialog-flutter-package
version: 0.0.9

environment:
  sdk: ^3.7.2
  flutter: ">=3.29.2"

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^6.1.0
  internet_connection_checker: ^3.0.1
  app_settings: ^6.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
   - assets/no_wifi.png
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
assets/no_internet:
  json:


keywords:
  - network
  - connectivity
  - offline
  - dialog
  - internet
  - auto dialog
  - connection lost
  - no internet
  - status handler
  - wifi alert
